require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'lib/tikkie/api/v1/**/*'
    - 'spec/tikkie/api/v1/**/*'
    - 'vendor/**/*'


Metrics/AbcSize:
  Max: 41

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 8


RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 8


Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
