plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'lib/tikkie/api/v1/**/*'
    - 'spec/tikkie/api/v1/**/*'
    - 'vendor/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 8

Style/SafeNavigation:
  Enabled: false
