require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'lib/tikkie/api/v1/**/*'
    - 'spec/tikkie/api/v1/**/*'
    - 'vendor/**/*'


Metrics/AbcSize:
  Max: 21

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false


RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleExpectations:
  Max: 4

RSpec/NamedSubject:
  Enabled: false


Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
