require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'lib/tikkie/api/v1/**/*'
    - 'spec/tikkie/api/v1/**/*'
    - 'vendor/**/*'


Layout/LineLength:
  Enabled: false


Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10


RSpec/FactoryBot:
  Enabled: false

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 8


Style/SafeNavigation:
  Enabled: false
